# 1
version: '3.8'
# 2
services: 
    db:
        image: mysql
        container_name: mysql
        ports: 
            - '3306:3306'
        # environment: 
        #     - 'MYSQL_ROOT_PASSWORD=12345678'
        env_file: common.env

# 3 OPTIONAL

# 4 OPTIONAL
