# 1
version: '3.8'
# 2
services: 
    web:
        container_name: web
        image: webtest
        # build: . #--busca dockerfile
        build: 
            context: ./otrodockerfile
            dockerfile: dockerfile2
    web2:
        container_name: web2
        image: webtest2
        # build: . #--busca dockerfile
        build: .
