# 1
version: '3.8'
# 2
services: 
    web:
        image: nginx
        container_name: nginx2
        ports: 
            - '8081:80'
        networks: 
            - net-test
    web2:
        image: nginx
        container_name: nginx3
        ports: 
            - '8082:80'
        networks: 
            - net-test
# 3 OPTIONAL

# 4 OPTIONAL
networks: 
    # Crear net-test
    net-test: