# 1
version: '3.8'
# 2
services: 
    web:
        image: nginx
        container_name: nginx2
        ports: 
            - '8081:80'
        volumes: 
            - '/home/samuel/Escritorio/Udemy/Dockers/dockers/docker-compose/volumenes-host/html:/usr/share/nginx/html'
# 3 OPTIONAL
# 4 OPTIONAL
